version: "3"

services:
  db-node:
    image: mariadb
    container_name: db-node
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db-node-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    networks:
      - arch-network

  auth-service:
    build:
      context: .
      dockerfile: docker/auth_service/Dockerfile
    container_name: auth-service
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SERVICE_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - arch-network
    depends_on:
      db-node:
        condition: service_healthy

  product-service:
    build:
      context: .
      dockerfile: docker/product_service/Dockerfile
    container_name: product-service
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SERVICE_PORT=8082
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
    ports:
      - "8082:8082"
    networks:
      - arch-network
    depends_on:
      db-node:
        condition: service_healthy

volumes:
  db-node-data:


networks:
  arch-network:
    driver: "bridge"
    external: false
